apiVersion: apps/v1
kind: Deployment
metadata:
  name: uporabniki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-catalog
  template:
    metadata:
      labels:
        app: image-catalog
    spec:
      containers:
      - image: sabinca97/novaslika:2
        name: image-catalog
        imagePullPolicy: Always
        env:
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://ec2-54-208-233-243.compute-1.amazonaws.com/d373nd6ijuq04e
        - name: KUMULUZEE_DATASOURCES0_USERNAME
          value: axmsufdwudxpwn
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          value: 550d2e28f70ccc901a7500c35a50cce651b356d13af4b6862468a80ea257fe9c
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/live
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3


---

apiVersion: v1
kind: Service
metadata:
  name: uporabniki-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: server
  selector:
    app: image-catalog


