kumuluzee:
  name: image-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
  - jndi-name: jdbc/axmsufdwudxpwn
    connection-url: jdbc:postgresql://ec2-54-208-233-243.compute-1.amazonaws.com/d373nd6ijuq04e
    username: axmsufdwudxpwn
    password: 550d2e28f70ccc901a7500c35a50cce651b356d13af4b6862468a80ea257fe9c
    listen_addresses: "*"
    pool:
      max-size: 5


  cors-filter:
    annotations:
      my-resource:
        allow-origin: "*"
        allow-generic-http-requests: true
        allow-subdomains: true
        supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"

rest-properties:
  maintenance-mode: false
  broken: false